kind: Secret
apiVersion: v1
metadata:
  name: mongodb
stringData:
  MONGODB_ADMIN_PASSWORD: {{ .Values.mongo.MONGODB_ADMIN_PASSWORD }}
  MONGODB_DATABASE: {{ .Values.mongo.MONGODB_DATABASE }}
  MONGODB_PASSWORD: {{ .Values.mongo.MONGODB_PASSWORD }}
  MONGODB_USER: {{ .Values.mongo.MONGODB_USER }}
type: Opaque