kind: Secret
apiVersion: v1
metadata:
  name: postgresql
  namespace: {{ .Values.postgresql.namespace }}
stringData:
  POSTGRESQL_DATABASE: {{ .Values.postgresql.POSTGRESQL_DATABASE }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.POSTGRESQL_PASSWORD }}
  POSTGRESQL_USER: {{ .Values.postgresql.POSTGRESQL_USER }}
type: Opaque